### ISSUE TITLE
Truffle deployment contracts error 

### ISSUE THREAD

**Issue by Alladin9393** [velas/velas-chain#50] opened 2021-01-12 14:30 UTC
#### Problem
Deploying contracts by truffle return error from the server:

Error code: `503 Service Unavailable`
Error message: `The server is currently unable to handle your request due to a temporary overload or scheduled maintenance.`

Contracts: https://github.com/velas/velas-id-contract

**Comment by vldm** [comment] 2021-01-29 12:29
Sometimes our rpc is stop working for some period of time caused by #56 
Looks like our reverse proxy handle this situation and sends this response.
Closed in favor of #56

**Closed as completed by vldm** 2021-01-29 12:29 UTC
Labels: bug
